import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import os from'node:os';
import{checkImages,readWebpDimensions}from'../scripts/check-images.mjs';
function chunk(type,payload){const b=Buffer.alloc(8+payload.length+(payload.length&1));b.write(type);b.writeUInt32LE(payload.length,4);payload.copy(b,8);return b;}
function webp(width=1024,height=768,type='VP8 ',extra=0){let p,chunks=[];if(type==='VP8L'){p=Buffer.alloc(5);p[0]=0x2f;p.writeUInt32LE((width-1)|((height-1)<<14),1);chunks.push(chunk('VP8L',p));}else{p=Buffer.alloc(10);Buffer.from([0x9d,1,0x2a]).copy(p,3);p.writeUInt16LE(width,6);p.writeUInt16LE(height,8);if(type==='VP8X'){const x=Buffer.alloc(10);x.writeUIntLE(width-1,4,3);x.writeUIntLE(height-1,7,3);chunks.push(chunk('VP8X',x));}chunks.push(chunk('VP8 ',p));}if(extra)chunks.push(chunk('JUNK',Buffer.alloc(extra)));const body=Buffer.concat([Buffer.from('WEBP'),...chunks]);const out=Buffer.alloc(8+body.length);out.write('RIFF');out.writeUInt32LE(body.length,4);body.copy(out,8);return out;}
function fixture({style='b',status='approved-image',bytes=webp(),write=true,prompt='Actual prompt'}={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'fq-image-check-'));fs.mkdirSync(path.join(root,'data'));fs.writeFileSync(path.join(root,'data/countries.js'),"window.FQ={countries:[{code:'kr'}]};");fs.mkdirSync(path.join(root,'docs/image-prompts/prompts'),{recursive:true});fs.writeFileSync(path.join(root,'docs/image-prompts/prompts/kr-symbol.txt'),prompt);fs.writeFileSync(path.join(root,'docs/image-prompts/presets.json'),JSON.stringify({styleChoice:style,items:[{id:'kr-symbol',code:'kr',kind:'symbol',status,bytes:bytes.length,outputStem:'images/symbols/kr'}]}));if(write){fs.mkdirSync(path.join(root,'images/symbols'),{recursive:true});fs.writeFileSync(path.join(root,'images/symbols/kr.webp'),bytes);}return root;}
function using(options,fn){const root=fixture(options);try{fn(root);}finally{fs.rmSync(root,{recursive:true,force:true});}}
test('WebP VP8·VP8L·VP8X는 실제 이미지 청크의 치수를 읽는다',()=>{for(const type of ['VP8 ','VP8L','VP8X'])assert.deepEqual(readWebpDimensions(webp(768,576,type)),{width:768,height:576});assert.deepEqual(readWebpDimensions(webp(1024,768,'VP8X',3)),{width:1024,height:768});});
test('RIFF 길이·키프레임·실제 청크 없는 canvas·canvas 속임수를 거부한다',()=>{const broken=webp();broken.writeUInt32LE(0,4);assert.throws(()=>readWebpDimensions(broken),/RIFF/);const keyframe=webp();keyframe[23]=0;assert.throws(()=>readWebpDimensions(keyframe),/키프레임/);const noImage=webp(1024,768,'VP8X').subarray(0,30);noImage.writeUInt32LE(noImage.length-8,4);assert.throws(()=>readWebpDimensions(noImage),/실제 이미지/);const mismatch=webp(800,600,'VP8X');mismatch.writeUIntLE(1023,24,3);mismatch.writeUIntLE(767,27,3);assert.throws(()=>readWebpDimensions(mismatch),/canvas/);const animated=webp(1024,768,'VP8X');animated[20]=2;assert.throws(()=>readWebpDimensions(animated),/애니메이션/);});
test('원장도 이미지도 없는 단계와 승인0건 null 화풍은 정상 통과한다',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'fq-image-empty-'));try{assert.equal(checkImages({root}).ok,true);}finally{fs.rmSync(root,{recursive:true,force:true});}using({status:'draft',style:null,write:false},root=>assert.equal(checkImages({root}).ok,true));using({},root=>assert.equal(checkImages({root}).ok,true));});
test('고아 파일과 미승인 그림은 실패하고 승인 그림의 누락도 실패한다',()=>{using({},root=>{fs.writeFileSync(path.join(root,'images/symbols/zz.webp'),webp());assert.ok(checkImages({root}).errors.some(e=>/고아 파일.*zz.webp/.test(e)));});using({status:'generated'},root=>assert.ok(checkImages({root}).errors.some(e=>/고아 파일/.test(e))));using({write:false},root=>assert.ok(checkImages({root}).errors.some(e=>/승인 그림 파일 누락/.test(e))));});
test('화풍 치수와 소수 없는 10진 KB 경고·상한을 검사한다',()=>{using({style:'a',bytes:webp(800,600)},root=>assert.ok(checkImages({root}).errors.some(e=>/치수 불일치 768×576 기대/.test(e))));using({bytes:webp(1024,768,'VP8 ',110000)},root=>{const r=checkImages({root});assert.equal(r.ok,true);assert.equal(r.warnings.length,1);});using({bytes:webp(1024,768,'VP8 ',150000)},root=>assert.ok(checkImages({root}).errors.some(e=>/용량 상한 초과/.test(e))));using({style:null},root=>assert.ok(checkImages({root}).errors.some(e=>/미선택/.test(e))));});
test('프롬프트 누락·원장 bytes 불일치·가짜확장자·심볼릭 링크를 거부한다',()=>{using({prompt:'  '},root=>assert.ok(checkImages({root}).errors.some(e=>/프롬프트 누락/.test(e))));using({},root=>{const packPath=path.join(root,'docs/image-prompts/presets.json'),p=JSON.parse(fs.readFileSync(packPath));p.items[0].bytes++;fs.writeFileSync(packPath,JSON.stringify(p));assert.ok(checkImages({root}).errors.some(e=>/bytes 불일치/.test(e)));});using({},root=>{fs.writeFileSync(path.join(root,'images/symbols/kr.png'),webp());assert.ok(checkImages({root}).errors.some(e=>/확장자 오류/.test(e)));fs.symlinkSync('kr.webp',path.join(root,'images/symbols/jp.webp'));assert.ok(checkImages({root}).errors.some(e=>/일반 WebP/.test(e)));});});
test('원장의 출력 경로가 지정된 이미지 폴더를 벗어나면 거부한다',()=>{using({},root=>{const packPath=path.join(root,'docs/image-prompts/presets.json'),p=JSON.parse(fs.readFileSync(packPath));p.items[0].outputStem='../../outside';fs.writeFileSync(packPath,JSON.stringify(p));assert.ok(checkImages({root}).errors.some(e=>/원장 항목 경로/.test(e)));p.items=[null];fs.writeFileSync(packPath,JSON.stringify(p));assert.ok(checkImages({root}).errors.some(e=>/항목은 객체/.test(e)));});});
